// import type { Metadata } from "next";
// import "./globals.css";
// import Navbar from "./components/Navbar";
// import Footer from "./components/Footer";
// import { Plus_Jakarta_Sans } from "next/font/google";
// const jakartaSans = Plus_Jakarta_Sans({
//   subsets: ["latin"],
//   weight: ["700"],
//   variable: "--font-jakarta",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html
//       lang="id"
//       className={`${jakartaSans.variable}`}
//       suppressHydrationWarning
//     >
//       <body
//         className="min-h-full flex flex-col items-center antialiased"
//         suppressHydrationWarning
//       >
//         <Navbar />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Plus_Jakarta_Sans } from "next/font/google";

// Tambahkan weight lain agar teks deskripsi tidak ikut jadi super tebal
const jakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-jakarta",
});

export const metadata: Metadata = {
  title: "Monify - Cara Baru Mengelola Uang",
  description: "Setiap rupiah tercatat, setiap keputusan lebih bijak.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="id"
      className={`${jakartaSans.variable}`}
      suppressHydrationWarning
    >
      <body
        className={`${jakartaSans.className} min-h-screen w-full flex flex-col items-center antialiased bg-[#FDFCFB] text-[#1E293B]`}
        suppressHydrationWarning
      >
        <Navbar />
        {/* Main element ditambahkan agar children mengisi ruang yang tersedia */}
        <main className="w-full flex-grow flex flex-col items-center">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
